version: "3.8"

services:

  postgres:
    build:
      context: ./postgres
      dockerfile: postgres.dockerfile
    container_name: CryptoPG
    env_file:
      - .env
    ports:
      - "5454:5432"
    volumes:
      - ./Data/Postgres/:/var/lib/postgresql/data
    networks:
      - name_net

  redis:
    image: redis:7.0.4
    container_name: CryptoRed
    env_file:
      - .env
    ports:
      - "2279:2279"
    command: redis-server --requirepass ${RED_PASS:?RED_PASS variable is not set} --save 20 1 --loglevel warning --port 2279
    volumes:
      - ./Data/Redis/data:/data
    networks:
      - name_net

  bot:
    build:
      context: ../CryptoBot
      dockerfile: ./bot.dockerfile
    env_file: .env
    container_name: CryptoBot
    depends_on:
      - postgres
      - redis
    ports:
      - "81:81"
    volumes:
      - ../CryptoBot:/CryptoBot
    networks:
      - name_net


networks:
  name_net:
    driver: bridge